_target_: src.opt.optimizer.GaussNewton
name: gn
step_size: 1e-3
linear_solver:
  _target_: src.opt.linear_solve.SparseConjugateGradientSolver
  max_iterations: 100
  tolerance: 1e-10
  use_preconditioner: true
