name: mast3r

### keypoint & descriptors
view:
  parameterization: rotvec
  descriptor: null
  mask: False
  mask_blur_iterations: 0
  resize: ${sfm.feature_matching.resize}

mast3r_wrapper:
  _target_: src.external.mast3r.MASt3RWrapper
  model_name: ${paths.checkpoints_dir}/mast3r/MASt3R_ViTLarge_BaseDecoder_512_catmlpdpt_metric.pth
  device: cuda
  resize: ${sfm.feature_matching.resize}
  subsample: 8
  border: 3

pair:
  min_matches: 20
  max_verified_matches: 1024
  repeat_geometric_verification: False
  geometric_verification:
    kind: essential
    prob: 0.999
    max_pixel_distance: 1.5 # 1920 / 640 = 3
    min_inlier_ratio: 0.25
  min_matches_after_verification: 15
  spurious_matches_keep_one_to_one: True
  symmetric_matching: False

# Optional parameters
resize: [512] # recommended for indoor scenes ([-1] for no resize)
resize_float: false
overwrite: true # whether to overwrite existing keypoints and matches
min_track_length: 3
