# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.DeviceStatsMonitor.html#lightning.pytorch.callbacks.DeviceStatsMonitor

device_stats_monitor:
  _target_: lightning.pytorch.callbacks.DeviceStatsMonitor
  cpu_stats: null # logs CPU stats only if CPU is the accelerator being used
