# @package _global_

# Modular Combined Cost Function Configuration
cost:
  _target_: src.opt.cost.CompositeCostFunction
  desc: "combined_cauchy"
  scale_jac: true
  sparse_jac: true

  reduction: "mean"

  dust3r_weight: 1.0
  dust3r_scale: 1.0

  weights:
    - 1.
    - ${cost.dust3r_weight}

  # List of cost functions to combine
  cost_functions:
    # BA cost function
    - _target_: src.opt.cost.BACostFunction
      loss_function:
        _target_: src.opt.loss.SquaredLoss
        loss_function:
          _target_: src.opt.loss.CauchyLoss
      chunk_size: null
      sparse_jac: ${cost.sparse_jac}
      image_space_residuals: true

    # DUSt3R cost function
    - _target_: src.opt.cost.DUSt3RCostFunction
      loss_function:
        _target_: src.opt.loss.ScaledLoss
        scale: ${cost.dust3r_scale}
        loss_function:
          _target_: src.opt.loss.SquaredLoss
          loss_function:
            _target_: src.opt.loss.CauchyLoss
      chunk_size: null
      sparse_jac: ${cost.sparse_jac}
